#!/usr/bin/env ruby
have_peco = system "command -v peco > /dev/null"

if have_peco
  # system "eval `githelp #{$*.join(' ')} | peco`"
  cmd = `githelp #{$*.join(' ')} | peco`.gsub(/^\s*/,'')
  puts cmd
  system cmd
else
  puts "pecoをインストールして下さい"
end
